# Generated by Django 3.2.18 on 2023-03-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='text',
        ),
    ]
